name: postgresql-operator-deploy

on:
  push:
    tags:
      - v*.**

  workflow_dispatch:
  
env:
  prefix:  vivlanwong

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker pull registry.opensource.zalan.do/acid/postgres-operator:v1.10.0
      - run: docker tag registry.opensource.zalan.do/acid/postgres-operator:v1.10.0 $prefix/postgres-operator:v1.10.0 
      - run: docker tag registry.opensource.zalan.do/acid/postgres-operator:v1.10.0 $prefix/postgres-operator:latest 
      - run: docker push $prefix/postgres-operator:v1.10.0 
      - run: docker push $prefix/postgres-operator:latest
