name: postgresql-operator-deploy

on:
  push:
    tags:
      - v*.**

  workflow_dispatch:
  
env:
  prefix:  vivlanwong
  postgres_operator_version:  v1.10.0
  postgres_operator_ui_version:  v1.10.0
  pgbouncerr_version:  master-27
  spilo_version: 3.0-p1
  logical_backup: v1.10.0

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker pull registry.opensource.zalan.do/acid/postgres-operator:$postgres_operator_version
      - run: docker tag registry.opensource.zalan.do/acid/postgres-operator:$postgres_operator_version $prefix/zalan_acid_postgres-operator:$postgres_operator_version
      - run: docker tag registry.opensource.zalan.do/acid/postgres-operator:$postgres_operator_version $prefix/zalan_acid_postgres-operator:latest 
      - run: docker push $prefix/zalan_acid_postgres-operator:$postgres_operator_version
      - run: docker push $prefix/zalan_acid_postgres-operator:latest
      
      - run: docker pull registry.opensource.zalan.do/acid/pgbouncer:$pgbouncerr_version
      - run: docker tag registry.opensource.zalan.do/acid/pgbouncer:$pgbouncerr_version $prefix/zalan_acid_pgbouncer:$pgbouncerr_version
      - run: docker tag registry.opensource.zalan.do/acid/pgbouncer:$pgbouncerr_version $prefix/zalan_acid_pgbouncer:latest 
      - run: docker push $prefix/zalan_acid_pgbouncer:$pgbouncerr_version
      - run: docker push $prefix/zalan_acid_pgbouncer:latest
      
      - run: docker pull  ghcr.io/zalando/spilo-15:$spilo_version
      - run: docker tag ghcr.io/zalando/spilo-15:$spilo_version $prefix/ghcr_zalando_spilo-15:$spilo_version
      - run: docker tag ghcr.io/zalando/spilo-15:$spilo_version $prefix/ghcr_zalando_spilo-15:latest 
      - run: docker push $prefix/ghcr_zalando_spilo-15:$spilo_version
      - run: docker push $prefix/ghcr_zalando_spilo-15:latest 

      - run: docker pull  registry.opensource.zalan.do/acid/logical-backup:$logical_backup
      - run: docker tag registry.opensource.zalan.do/acid/logical-backup:$logical_backup $prefix/zalando_acid_logical-backup:$logical_backup
      - run: docker tag registry.opensource.zalan.do/acid/logical-backup:$logical_backup $prefix/zalando_acid_logical-backup:latest 
      - run: docker push $prefix/zalando_acid_logical-backup:$logical_backup
      - run: docker push $prefix/zalando_acid_logical-backup:latest 
      
      - run: docker pull registry.opensource.zalan.do/acid/postgres-operator-ui:$postgres_operator_ui_version
      - run: docker tag registry.opensource.zalan.do/acid/postgres-operator-ui:$postgres_operator_ui_version $prefix/zalando_acid_postgres-operator-ui:$postgres_operator_ui_version
      - run: docker tag registry.opensource.zalan.do/acid/postgres-operator-ui:$postgres_operator_ui_version $prefix/zalando_acid_postgres-operator-ui:latest 
      - run: docker push $prefix/zalando_acid_postgres-operator-ui:$postgres_operator_ui_version
      - run: docker push $prefix/zalando_acid_postgres-operator-ui:latest 
